version: "3"
services:
    app:
        restart: always
        build: .
        ports:
            - "3000:3000"
        environment:
            PORT: 3000
            user: root
            pass: example   # Should work out how to do this securely
        volumes:
            - /etc/letsencrypt/live/ricksterhd123.studio/privkey.pem:/usr/src/app/ssl/privkey.pem
            - /etc/letsencrypt/live/ricksterhd123.studio/fullchain.pem:/usr/src/app/ssl/fullchain.pem
    mongo:
        image: mongo
        restart: always
        # todo: volumes later
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
